version: 2.1

executors:
  android_executor:
    machine:
      image: ubuntu-1604:202007-01
    resource_class: 2xlarge
    working_directory: ~/geekbench-ci

jobs:
  bm:
    executor: android_executor
    steps:
      - checkout
      - run:
          name: Run geekbench
          command: pwd; ls -lha; sh ./run.sh
          no_output_timeout: 30m
workflows:
  version: 2
  master-flow:
    jobs:
      - bm:
          filters:
            branches:
              only:
                - master